
[functions.sync-espn-games]
enabled = true
verify_jwt = false
import_map = "./functions/sync-espn-games/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-espn-games/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-espn-games/*.html" ]

[functions.send-bracket-reminders]
enabled = true
verify_jwt = false
import_map = "./functions/send-bracket-reminders/deno.json"
entrypoint = "./functions/send-bracket-reminders/index.ts"

[functions.manage-tournament-launch]
enabled = true
verify_jwt = false
import_map = "./functions/manage-tournament-launch/deno.json"
entrypoint = "./functions/manage-tournament-launch/index.ts"
